name: MobArenaQuests
version: 2.1
description: Quests module for MobArena
author: Browsit
website: https://github.com/Browsit/MobArenaQuestsModule

main: org.browsit.mobarenaquests
depend: [MobArena, Quests]